/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package taskmanager;

import java.awt.Color;
import java.awt.Component;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author USER
 */
public class Main extends javax.swing.JFrame {

    public static Main ins;
    String user = store.strr;
    String qq,ee,aa,ss,dd;
    int ww,zz;
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        setResizable(false);
        ins = this;
        
        for (int i=0; i<3; i++) {
            TableColumn column = jTable1.getColumnModel().getColumn(i);
            if (i==0) column.setPreferredWidth(5);
            if (i==1) column.setPreferredWidth(500);
            if (i==2) column.setPreferredWidth(50);
            if (i==3) column.setPreferredWidth(30);
        }
        view();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main Menu");
        setAlwaysOnTop(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("MAIN MENU");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 260, -1));

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("CALENDAR");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 260, 80));

        jLabel7.setIcon(new javax.swing.ImageIcon("E:\\2-2\\icons\\clkb.png")); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));
        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("DIARY");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        jPanel7.setBackground(new java.awt.Color(51, 51, 51));
        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel7MouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("USER DETAILS");

        jPanel8.setBackground(new java.awt.Color(51, 51, 51));
        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel8MouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("MAIN MENU");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 580));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Priority", "Task", "Finishing Date", "Time"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable1.setSelectionBackground(new java.awt.Color(102, 102, 255));
        jTable1.setShowGrid(false);
        jTable1.setShowVerticalLines(true);
        jTable1.getTableHeader().setResizingAllowed(false);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable1);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 820, 430));

        jTextField1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder("search"), null));
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        jPanel3.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 32, 820, 60));

        jToggleButton1.setIcon(new javax.swing.ImageIcon("E:\\2-2\\icons\\finish.png")); // NOI18N
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 390, 30, 30));

        jButton1.setIcon(new javax.swing.ImageIcon("E:\\2-2\\icons\\more.png")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 230, 30, 30));

        jButton2.setIcon(new javax.swing.ImageIcon("E:\\2-2\\icons\\plus-symbol-button.png")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 110, 30, 30));

        jButton3.setIcon(new javax.swing.ImageIcon("E:\\2-2\\icons\\recycle-bin.png")); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 150, 30, 30));

        jButton4.setIcon(new javax.swing.ImageIcon("E:\\2-2\\icons\\refresh.png")); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 190, 30, 30));

        jButton5.setIcon(new javax.swing.ImageIcon("E:\\2-2\\icons\\check-mark.png")); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 270, 30, 30));

        jButton6.setIcon(new javax.swing.ImageIcon("E:\\2-2\\icons\\writing.png")); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 350, 30, 30));

        jButton7.setIcon(new javax.swing.ImageIcon("E:\\2-2\\icons\\close.png")); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 310, 30, 30));

        jButton8.setIcon(new javax.swing.ImageIcon("E:\\2-2\\icons\\question.png")); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 430, 30, 30));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 890, 580));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        if(jToggleButton1.isSelected()){
            view();
            changer();
        }
        else{
            dispose();
            Main b = new Main();
            b.setVisible(true);
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseClicked
        // TODO add your handling code here:
        calendar pi = new calendar();
        pi.setVisible(true);
        dispose();
    }//GEN-LAST:event_jPanel5MouseClicked

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        // TODO add your handling code here:
        String loc = jTextField1.getText();
        try{
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/task","root","1234");
            String sql = "select * from " + user + " where task like '%"+loc+"%'";
            PreparedStatement ptst = c.prepareStatement(sql);
            ResultSet rs = ptst.executeQuery();
            
            DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
            model.setRowCount(0);
            while(rs.next()){
                if(rs.getInt(8)==1){
                    model.addRow(new String[] {rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5)});
                }
            }
            c.close();
        }
        catch(SQLException ex){
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jPanel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jPanel8MouseClicked

    private void jPanel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseClicked
        // TODO add your handling code here:
        Details pi = new Details();
        pi.setVisible(true);
        dispose();
    }//GEN-LAST:event_jPanel7MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        AddMenu pi = new AddMenu();
        pi.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        dispose();
        Main b = new Main();
        b.setVisible(true);
        notification.inss.load();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        remover();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        int stat = 0,stat2 = 0,ann=0,flag=0;
        int row = jTable1.getSelectedRow();
        String q = jTable1.getModel().getValueAt(row, 0).toString();
        String x = jTable1.getModel().getValueAt(row, 2).toString();
        String t = jTable1.getModel().getValueAt(row, 3).toString();
        String da = x.substring(0,4)+x.substring(5,7)+x.substring(8,10)+q+t.substring(0,2)+t.substring(3,5);
        String tmp = t.substring(6,8);
        if(tmp.equals("AM")){
            da = da + "0";
        }
        else{
            da = da + "1";
        }
        try{
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/task","root","1234");
            String sql = "select * from " + user + " where id = "+da;
            PreparedStatement ptst = c.prepareStatement(sql);
            ResultSet rs = ptst.executeQuery();
            while(rs.next()){
                stat = rs.getInt(8);
                stat++;
                ann = rs.getInt(7);
                qq = rs.getString(1);
                ww = rs.getInt(2);
                ee = rs.getString(3);
                aa = rs.getString(4);
                ss = rs.getString(5);
                dd = rs.getString(6);
                zz = ann;
            }
            c.close();
            if(ann == 1){
                anniver();
                flag = 1;
            }
            
            c = DriverManager.getConnection("jdbc:mysql://localhost:3306/task","root","1234");
            sql = "update "+ user +" set status = ? where id = ?";
            ptst = c.prepareStatement(sql);
            ptst.setInt(1,stat);
            ptst.setString(2,da);
            ptst.executeUpdate();
            c.close();
            c = DriverManager.getConnection("jdbc:mysql://localhost:3306/task","root","1234");
            sql = "Select *from account where username = '"+user+"'";
            ptst = c.prepareStatement(sql);
            rs = ptst.executeQuery();
            while(rs.next()){
                stat2 = rs.getInt(7);
                stat2++;
                stat = rs.getInt(6);
                if(flag == 1){
                    stat++;
                }
            }
            c.close();
            c = DriverManager.getConnection("jdbc:mysql://localhost:3306/task","root","1234");
            sql = "update account set cmplted = ?,added = ? where username = ?";
            ptst = c.prepareStatement(sql);
            ptst.setInt(1,stat2);
            ptst.setString(3,user);
            ptst.setInt(2,stat);
            ptst.executeUpdate();
            c.close();
            JOptionPane.showMessageDialog(this, "Task marked as Completed!!!");
            view();
        }
        catch(SQLException ex){
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        fclist pi = new fclist();
        pi.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();
        String q = jTable1.getModel().getValueAt(row, 0).toString();
        String x = jTable1.getModel().getValueAt(row, 2).toString();
        String t = jTable1.getModel().getValueAt(row, 3).toString();
        String da = x.substring(0,4)+x.substring(5,7)+x.substring(8,10)+q+t.substring(0,2)+t.substring(3,5);
        String tmp = t.substring(6,8);
        if(tmp.equals("AM")){
            da = da + "0";
        }
        else{
            da = da + "1";
        }
        //jLabel1.setText(da);
        store.idfm = da;
        more pi = new more();
        pi.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked
        // TODO add your handling code here:
        diaryy d = new diaryy();
        d.setVisible(true);
        dispose();
    }//GEN-LAST:event_jPanel6MouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        int stat = 0,stat2=0,ann=0,flag = 0;
        int row = jTable1.getSelectedRow();
        String q = jTable1.getModel().getValueAt(row, 0).toString();
        String x = jTable1.getModel().getValueAt(row, 2).toString();
        String t = jTable1.getModel().getValueAt(row, 3).toString();
        String da = x.substring(0,4)+x.substring(5,7)+x.substring(8,10)+q+t.substring(0,2)+t.substring(3,5);
        String tmp = t.substring(6,8);
        if(tmp.equals("AM")){
            da = da + "0";
        }
        else{
            da = da + "1";
        }
        try{
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/task","root","1234");
            String sql = "select * from " + user + " where id = "+da;
            PreparedStatement ptst = c.prepareStatement(sql);
            ResultSet rs = ptst.executeQuery();
            while(rs.next()){
                stat = rs.getInt(8);
                stat++;
                stat++;
                ann = rs.getInt(7);
                qq = rs.getString(1);
                ww = rs.getInt(2);
                ee = rs.getString(3);
                aa = rs.getString(4);
                ss = rs.getString(5);
                dd = rs.getString(6);
                zz = ann;
            }
            c.close();
            if(ann == 1){
                anniver();
                flag = 1;
            }
            c = DriverManager.getConnection("jdbc:mysql://localhost:3306/task","root","1234");
            sql = "update "+ user +" set status = ? where id = ?";
            ptst = c.prepareStatement(sql);
            ptst.setInt(1,stat);
            ptst.setString(2,da);
            ptst.executeUpdate();
            c.close();
            c = DriverManager.getConnection("jdbc:mysql://localhost:3306/task","root","1234");
            sql = "Select *from account where username = '"+user+"'";
            ptst = c.prepareStatement(sql);
            rs = ptst.executeQuery();
            while(rs.next()){
                stat2 = rs.getInt(8);
                stat2++;
                stat = rs.getInt(6);
                if(flag == 1){
                    stat++;
                }
            }
            c.close();
            c = DriverManager.getConnection("jdbc:mysql://localhost:3306/task","root","1234");
            sql = "update account set failed = ?,added = ? where username = ?";
            ptst = c.prepareStatement(sql);
            ptst.setInt(1,stat2);
            ptst.setInt(2,stat);
            ptst.setString(3,user);
            ptst.executeUpdate();
            c.close();
            JOptionPane.showMessageDialog(this, "Task marked as Failed!!!");
            view();
        }
        catch(SQLException ex){
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        help d = new help();
        d.setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    public void view(){
        try{
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/task","root","1234");
            String sql = "select * from " + user + " ORDER BY id";
            PreparedStatement ptst = c.prepareStatement(sql);
            ResultSet rs = ptst.executeQuery();
            
            DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
            model.setRowCount(0);
            while(rs.next()){
                if(rs.getInt(8)==1){
                    model.addRow(new String[] {rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5)});
                }
            }
            c.close();
        }
        catch(SQLException ex){
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void changer(){
        //jTable1.setBackground(Color.red);
        jTable1.setDefaultRenderer(Object.class, new DefaultTableCellRenderer(){
        @Override
        public Component getTableCellRendererComponent(JTable table,Object value, boolean isSelected, boolean hasFocus, int row, int col) {

            super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, col);
            Date d = new Date();
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        
            String dd = sdf.format(d);
            String status = (String)table.getModel().getValueAt(row, 2);
            setBackground(new Color(255, 150, 150));
            if (dd.equals(status)) {
                setBackground(new Color(145, 255, 170));
                setForeground(jTable1.getForeground());
            }
            else if (dd.compareTo(status)>0) {
                setBackground(new Color(255, 150, 150));
                setForeground(jTable1.getForeground());
            }
            else{
                setBackground(jTable1.getBackground());
                setForeground(jTable1.getForeground());
            }
            return this;
        }   
});
    }
    
    public void remover(){
        int stat =0;
        int row = jTable1.getSelectedRow();
        String q = jTable1.getModel().getValueAt(row, 0).toString();
        String x = jTable1.getModel().getValueAt(row, 2).toString();
        String t = jTable1.getModel().getValueAt(row, 3).toString();
        String da = x.substring(0,4)+x.substring(5,7)+x.substring(8,10)+q+t.substring(0,2)+t.substring(3,5);
        String tmp = t.substring(6,8);
        if(tmp.equals("AM")){
            da = da + "0";
        }
        else{
            da = da + "1";
        }
        //jLabel1.setText(da);
        try{
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/task","root","1234");
            String sql = "delete from " + user + " where id="+da;
            PreparedStatement ptst = c.prepareStatement(sql);
            ptst.executeUpdate();
            c.close();
            c = DriverManager.getConnection("jdbc:mysql://localhost:3306/task","root","1234");
            sql = "Select *from account where username = '"+user+"'";
            ptst = c.prepareStatement(sql);
            ResultSet rs = ptst.executeQuery();
            while(rs.next()){
                stat = rs.getInt(6);
                stat--;
            }
            c.close();
            c = DriverManager.getConnection("jdbc:mysql://localhost:3306/task","root","1234");
            sql = "update account set added = ? where username = ?";
            ptst = c.prepareStatement(sql);
            ptst.setInt(1,stat);
            ptst.setString(2,user);
            ptst.executeUpdate();
            c.close();
            JOptionPane.showMessageDialog(this, "Task Deleted!!!");
            view();
        }
        catch(SQLException ex){
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void anniver(){
        try{
            String tmp;
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/task","root","1234");
            String sql = "insert into " + user + " (id,priority,task,date,time,ann,descr) values(?,?,?,?,?,?,?)";
            PreparedStatement ptst = c.prepareStatement(sql);
            tmp = qq.substring(4);
            qq = Integer.toString(Integer.parseInt(qq.substring(0,4))+1);
            qq = qq + tmp;
            ptst.setString(1,qq);
            ptst.setInt(2,ww);
            ptst.setString(3,ee);
            tmp = aa.substring(4);
            aa = Integer.toString(Integer.parseInt(aa.substring(0,4))+1);
            aa = aa + tmp;
            ptst.setString(4,aa);
            ptst.setString(5,ss);
            ptst.setString(7,dd);
            ptst.setInt(6,zz);
            ptst.execute();
            c.close();
        }
        catch(SQLException ex){
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
